apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exp
  labels:
    app: mongo-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      name: mongo-exp
      labels:
        app: mongo-exp
    spec:
      containers:
        - name: mongo-exp
          image: mongo-express
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-global
                  key: mongo-exp-usr
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-global
                  key: mongo-exp-pwd
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: mongo-url



---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exp-service
spec:
  selector:
    app: mongo-exp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer